/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestApp;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest2 {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    // @Test
    // public void testAppHasAGreeting2() {
    // // App classUnderTest = new App();
    // assertNotNull("app should have a greeting", null);
    // }
    @Test
    public void testAppHasAGreeting3() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting 3", classUnderTest.getGreeting());
    }

}
